### ISSUE TITLE
DependencyConflict Starlette

### ISSUE THREAD

**Issue by JNygaard-Skylight** [CDCgov/dibbs-ecr-viewer#713]
## Description

In the v3.4.0 orchestration image the following warning log appears in orchestration:
```log
DependencyConflict: requested: starlette >=0.13, <0.15" but found "starlette 0.46.2"
```

## Steps to reproduce

Build orchestration using image: `ghcr.io/cdcgov/dibbs-ecr-viewer/orchestration:3.4`. I did this by replacing the following lines in `containers/ecr-viewer/seed-scripts/docker-compose-seed.yaml`:
```yaml
  orchestration-service:
    platform: linux/amd64
    build:
      context: ../../orchestration/
```
with:
```yaml
  orchestration-service:
    platform: linux/amd64
    image: ghcr.io/cdcgov/dibbs-ecr-viewer/orchestration:3.4
```

## Expected Result

Orchestration builds with no warnings or errors.

## Actual result
```log
DependencyConflict: requested: starlette >=0.13, <0.15" but found "starlette 0.46.2"
```

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority

- [x] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

This was caused by Python dependency shenanigans with updates involving Starlette, FastAPI, and OpenTelemetry. This was quickly resolved with an update to OpenTelemetry. In the interest of completeness, we can guarantee we do not see this by updating our OpenTelemetry dependencies in Orchestration.

Ideally there should be some kind of check for bad dependencies, but OpenTelemetry appears to check dependencies at runtime. Another solution is to use lock files so that dependencies do not magically update unless we tell them to. [See this follow-up ticket: #715
